import mongoose from 'mongoose';

/**
 * @model IssuedCertificate
 *
 * Stores ONLY the issuance/tracking record for official certificates.
 * The actual certificate HTML/PDF is NEVER stored here — it is generated
 * at runtime by injecting this record's data into the selected frontend template.
 *
 * Architecture: Database → Issue Record → Frontend Template → Runtime HTML → Print/PDF
 */
const IssuedCertificateSchema = new mongoose.Schema(
  {
    // ── Certificate Identity ─────────────────────────────────────────────────

    /**
     * Human-readable, globally unique certificate number.
     * Format: CERT-{YEAR}-{6-digit-sequence} e.g. CERT-2026-000001
     * Generated by the controller at issue time.
     */
    certificateNumber: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
      index: true,
    },

    /**
     * The type of certificate issued.
     * BONAFIDE     — confirms student is currently enrolled
     * CHARACTER    — character/conduct certificate
     * ACHIEVEMENT  — academic/sports/activity achievement
     * PARTICIPATION — event/program participation
     * TC           — transfer certificate
     * CUSTOM       — any other custom certificate type
     */
    certificateType: {
      type: String,
      required: true,
      enum: ['BONAFIDE', 'CHARACTER', 'ACHIEVEMENT', 'PARTICIPATION', 'TC', 'CUSTOM'],
      uppercase: true,
    },

    // ── Template Reference ───────────────────────────────────────────────────

    /**
     * The frontend template ID used when this certificate was issued.
     * Stored so re-rendering can use the same design as the original issuance.
     * Example: "certificate-classic-v1"
     */
    templateId: {
      type: String,
      required: true,
      trim: true,
    },

    /**
     * Template version at the time of issuance.
     * Prevents silent design changes from affecting previously issued certificates.
     */
    templateVersion: {
      type: String,
      default: 'v1',
      trim: true,
    },

    // ── Recipient Information ────────────────────────────────────────────────

    /** Whether the recipient is a student, teacher, or other staff member. */
    recipientType: {
      type: String,
      required: true,
      enum: ['student', 'teacher', 'staff'],
      lowercase: true,
    },

    /**
     * MongoDB ObjectId of the recipient document.
     * For students → Student._id, for teachers → Teacher._id, for staff → User._id.
     * Stored for audit & re-render lookups but snapshot fields are the source of
     * truth for historical accuracy.
     */
    recipientId: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      index: true,
    },

    /**
     * Snapshot of the recipient's full name at the time of issuance.
     * If the name is later corrected, the issued record still reflects the
     * original name for historical accuracy.
     */
    recipientNameSnapshot: {
      type: String,
      required: true,
      trim: true,
    },

    /**
     * Snapshot of the recipient's institutional ID (admission number,
     * employee ID, etc.) at issuance time.
     */
    recipientIdSnapshot: {
      type: String,
      trim: true,
    },

    /**
     * Additional snapshot data captured at issuance time.
     * Students: class, section, academicYear, rollNumber, bloodGroup, etc.
     * Teachers: department, designation, etc.
     */
    additionalSnapshot: {
      type: mongoose.Schema.Types.Mixed,
      default: {},
    },

    // ── Academic Context ─────────────────────────────────────────────────────

    /** The academic session in which the certificate was issued. e.g. "2026-27" */
    academicSession: {
      type: String,
      trim: true,
    },

    // ── Issuance Audit Trail ─────────────────────────────────────────────────

    /** The User who issued this certificate (Admin/Principal). */
    issuedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },

    issuedAt: {
      type: Date,
      default: Date.now,
    },

    // ── Certificate Status ───────────────────────────────────────────────────

    /**
     * VALID   — certificate is active and verifiable
     * REVOKED — certificate has been cancelled (record preserved for audit)
     * EXPIRED — certificate has passed its validity date (if applicable)
     */
    status: {
      type: String,
      enum: ['VALID', 'REVOKED', 'EXPIRED'],
      default: 'VALID',
      uppercase: true,
    },

    // ── Verification Token ───────────────────────────────────────────────────

    /**
     * Secure random token used in the QR code for public verification.
     * URL: /verify/certificate/{verificationToken}
     * The token is opaque and does NOT expose internal database IDs.
     */
    verificationToken: {
      type: String,
      unique: true,
      index: true,
    },

    // ── Revocation Details ───────────────────────────────────────────────────

    /**
     * Populated when status becomes REVOKED.
     * The original record is NEVER deleted — it is preserved for audit purposes.
     */
    revokedAt: { type: Date },
    revokedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    revocationReason: { type: String, trim: true },

    // ── Optional Purpose/Notes ───────────────────────────────────────────────

    /** Optional custom text injected into the certificate body. */
    purposeNote: { type: String, trim: true },
  },
  { timestamps: true }
);

// Efficient lookups by recipient across types and statuses
IssuedCertificateSchema.index({ recipientId: 1, recipientType: 1, status: 1 });
// Year-wise ordering for certificate number sequence generation
IssuedCertificateSchema.index({ issuedAt: -1 });

export default mongoose.model('IssuedCertificate', IssuedCertificateSchema);
